version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.9.1
